apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: voting
data:
  REDIS_HOST: "redis-master"
  REDIS_PORT: "6379"
  POSTGRES_HOST: "postgres"
  POSTGRES_DB: "votes"
  POSTGRES_USER: "postgres"

